name: barberias
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  generic_bloc_provider: ^1.0.9
  firebase_auth:
  google_sign_in:
  firebase_storage: ^2.1.0
  cloud_firestore: ^0.9.13
  carousel_pro: ^1.0.0
  url_launcher: ^5.5.0
  geolocator: ^5.3.2+2
  flutter_map:
  google_maps_flutter: ^0.5.28+1
  permission_handler: ^5.0.1
  location: ^3.0.2
  map_controller: ^0.8.0
  curved_navigation_bar: ^0.3.2
  image_picker: ^0.6.7+1
  cached_network_image: ^2.2.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/corte_cachetada.jpg
    - assets/images/corte_raya.jpg
    - assets/images/corte_degradado.jpg
    - assets/images/corte_colita.png
    - assets/images/imagenUno.jpg
    - assets/images/imagenDos.jpg
    - assets/images/imagenTres.jpg
    - assets/images/imagenCuatro.jpg
    - assets/images/imagenCinco.jpg
    - assets/images/imagenSeis.jpg
    - assets/images/bimba.jpg
    - assets/images/beso_bimba.jpg
    - assets/images/bimba_otra.jpg
    - assets/images/logo_oficial.jpg
    - assets/images/promotions.jpg
    - assets/images/fondo_login.jpg
    - assets/images/fondo_loginDos.jpg
    - assets/images/pin_ubicacion.png
    - assets/images/iconoo_app.jpg

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
